language: ruby
cache: bundler
rvm: 2.5

before_install:
  - gem update --system --no-document
  - gem install bundler --no-document

script: script/cibuild

env:
  matrix:
    - JEKYLL_VERSION="~> 3.8.0"
    - JEKYLL_VERSION="~> 3.9"
    - JEKYLL_VERSION="~> 4.0"
